### ISSUE TITLE
Scheduling not working properly

### ISSUE THREAD

**Issue by byseeing** [ApolloZhu/Dynamic-Dark-Mode#57] opened 2019-02-27 01:29 UTC
I'm sure how to title this issue because I'm not certain what the problem is. My situation, as you'll see in the screenshot, is that night mode is triggered before the scheduled time. You can see that despite having selected Dark Mode On Between Official Sunset Sunrise (5:59 PM – 6:42 AM), it has triggered at 5:20 PM. I'd like to add that I love your product – thanks for making and maintaining it 🙏🏻
![Uploading Screenshot 2019-02-26 17.20.56.png…]()

**Comment by ApolloZhu** [comment] 2019-02-28 12:47
I can’t see the screen shot but what could have happened here is Dark Mode been turned on because screen brightness is below the triggering threshold. Do you think that might be the cause?

**Comment by byseeing** [comment] 2019-03-02 00:30
I don't believe that brightness has anything to do with it. I've turned off automatic brightness, and I just caught it switching too early again without any brightness changes. Here's a [link](https://www.dropbox.com/s/xnf2hspbjqgxuc5/Screenshot%202019-02-26%2017.20.56.png?dl=0) to the screenshot instead of an attachment.

**Comment by ApolloZhu** [comment] 2019-03-02 15:17
I can't think of a reason why that would happen, but I'll take a look at the code and try to see if there's anything wrong with it. Maybe you can try the latest release (1.1.4) and see if it fixes the problem. 1.1 (3) and earlier versions all have the problem that it'll schedule whenever your Mac awakes from sleep. But I think that and the situation you described are unrelated.

By the way the link is still not working, it's not publicly shared.

**Comment by byseeing** [comment] 2019-04-11 01:29
Looks like I was on an outdated version. Updated and I'll let you know if this behavior persists.

**Comment by ApolloZhu** [comment] 2019-05-17 21:10
Please reopen the issue if this happens again.

**Comment by byseeing** [comment] 2019-06-13 00:25
Hey, not sure how to re-open this, but I'm still having the schedule issue. Prefs say 8:30 pm but it's 5:20 pm and it flipped out. Been happening regularly. Running v1.1.4 on MacOS 10.14.5 (18F132).

**Comment by ApolloZhu** [comment] 2019-06-13 00:36
Do you mind trying out 1.3.0?

**Comment by ApolloZhu** [comment] 2019-06-13 00:38
And, does this happen immediately after you open/login/wake up your computer?

**Comment by byseeing** [comment] 2019-07-03 00:33
Hey there, I'll try 1.3.0. Currently, I'm on still on v1.1.4. At 5:30 PM on my shuttle ride home it switched on its own again. I'll report back after a few days on v1.3.0.

**Comment by byseeing** [comment] 2019-07-24 01:00
Hey there, I've been on 1.3.0 for some time now and I'm still experiencing this issue. 

I want to add another piece of information, in case it's helpful. Around the time that Dark Mode is triggered I'm also boarding a shuttle home from work that has wifi. This could be related or not.

Are there logs that I can provide you that would be helpful?

**Comment by byseeing** [comment] 2019-07-30 00:17
Indeed, the switch to dark mode appears to correspond with my move to my shuttle. Today the switch occurred at 5:11 PM PDT, after boarding the shuttle and opening my laptop. Oddly, I had not yet switched to shuttle wifi.

**Comment by byseeing** [comment] 2019-07-31 00:14
I'd like to add that it seems Dynamic Dark mode begins cycling between day and night modes when I board my shuttle. This slows my computer down until I quit the plugin.

**Comment by ApolloZhu** [comment] 2019-09-08 07:11
A recent change in Dynamic Dark Mode updates appearance on network condition change, so it sounds like the Wi-Fi on your shuttle provides inaccurate location information... I'll see how I should approach this...

Sorry for the late reply... My old computer broke and I just got hands on the new one yesterday.

**Comment by byseeing** [comment] 2019-09-20 02:37
Dude you're all good. Still really appreciate that you support this app
actively.  





On Sun, Sep 8, 2019 7:11 AM, ApolloZhu notifications@github.com  wrote:
A recent change in Dynamic Dark Mode updates appearance on network condition
change, so it sounds like the Wi-Fi on your shuttle provides inaccurate location
information... I'll see how I should approach this...

Sorry for the late reply... My old computer broke and I just got hands on the
new one yesterday.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.





⚡️ Brooks Hassig / Product Designer, Facebook

**Comment by ApolloZhu** [comment] 2019-09-22 00:10
Actually, now I'm in Seattle I'm able to reproduce/debug this issue myself. Thanks for your support and reporting this bug.

**Comment by ApolloZhu** [comment] 2019-09-24 01:37
Finally, it should be fixed. Update to 1.5.2 and see if it works ;)

**Closed by ApolloZhu** 2019-09-24 01:37 UTC
Labels: priority: fixed, type: bug
